### PR TITLE
Support comma separated filter arguments

### PR DESCRIPTION
**Pull request by mlaszloffy**

### CODE REVIEW

**Comment by sqwci** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [Bcl2fastqDeciderCli.java#L378](https://github.com/oicr-gsi/bcl2fastq/blob/1ee92bcaa0eac2fbfa754c842de98a78bbe5f221/decider-bcl2fastq/src/main/java/ca/on/oicr/pde/deciders/Bcl2fastqDeciderCli.java#L378): Use a logger to log this exception. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1148)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sqwci** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] [Bcl2fastqDeciderCli.java#L378](https://github.com/oicr-gsi/bcl2fastq/blob/2087e3606857016e0f3bb3702eeab9a29ef7d7ce/decider-bcl2fastq/src/main/java/ca/on/oicr/pde/deciders/Bcl2fastqDeciderCli.java#L378): Use a logger to log this exception. [rule](https://sonarcloud.io/coding_rules#rule_key=squid%3AS1148)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by mlaszloffy** [comment]
please retest this

**Comment by mlaszloffy** [comment]
retest this please

**Pull request merged**
