### PR TITLE
Updating CHANGELOG

### PR DESCRIPTION
**Pull request by pruzanov**

### CODE REVIEW

**Comment by hannahdriver** [comment]
The changes look fine to me, but the regression test is failing

**Review by hannahdriver — APPROVED** [review]

**Comment by avarsava** [comment]
The sum changes from all commits includes no vidarr label related changes, only regression test compatibility changes. I am not sure what I am reviewing.

**Comment by pruzanov** [comment]
> The sum changes from all commits includes no vidarr label related changes, only regression test compatibility changes. I am not sure what I am reviewing.

There ano changes with respect to vidarr_labels, only CHANGELOG reformatting and minor fixes to RT setup file. We have only one compound output, so old syntax in output_meta stays in place, as discussed

**Comment by avarsava** [comment]
Then please rewrite the git history so that labels are never mentioned rather than having commits which add then subsequently remove the labels.

**Comment by avarsava** [comment]
I meant more like
```
git reset master // only 'git reset --hard' destroys changes, this sets the state at the latest commit to be in staging
git add CHANGELOG.md
git commit -m "Fix CHANGELOG.md format"
git add vidarrtest-regression.json.in
git commit -m "Fixing RT setup"
git push --force
```
To clean the history of redundant commits, but ok

**Review by avarsava — APPROVED** [review]

**Pull request merged**
